name: Nightclub2.0
version: ${revision}
main: exposed.hydrogen.nightclub.NightclubSpigot
api-version: 1.18
authors: [ hydrogen ]
description: Nightclub 2.0
depend: [ ProtocolLib ]

commands:
  light:
    description: light builder + editor
    usage: /light
    permission: nightclub.light
  lightuniverse:
    description: light universe builder + editor
    usage: /lightuniverse
    permission: nightclub.lightuniverse
  beatmap:
    description: beatmap player
    usage: /beatmap
    permission: nightclub.beatmap
  ring:
    description: ring builder + editor
    usage: /ring
    permission: nightclub.ring

permissions:
  nightclub.light:
    description: Access to /light which is the builder and editor
    default: op
  nightclub.lightuniverse:
    description: Access to /lightuniverse which is the lightuniverse builder and editor
    default: op
  nightclub.beatmap:
    description: Access to /beatmap which is the beatmap player command itself
    default: op
  nightclub.ring:
    description: Access to /ring which is the ring builder and editor
    default: op
